CREATE TABLE "mytable" (
  "CREATE TABLE transactions (" text
);

INSERT INTO "mytable" ("CREATE TABLE transactions (")
VALUES
('transaction_id VARCHAR(10) PRIMARY KEY'),
('transaction_date DATE'),
('merchant_name VARCHAR(100)'),
('raw_amount DECIMAL(18'),
('currency VARCHAR(5)'),
('usd_amount DECIMAL(18'),
('status VARCHAR(50)'),
('risk_score INT'),
('gateway_region VARCHAR(10)'),
('user_id VARCHAR(10)'),
('payment_method VARCHAR(50)'),
('high_value_flag INT'),
('high_risk_flag INT'),
(');'),
('INSERT INTO transactions ('),
('transaction_id'),
('usd_amount'),
('payment_method'),
(')'),
('VALUES'),
('(''T001'''),
('(''T002'''),
('(''T003'''),
('(''T004'''),
('(''T005'''),
('(''T006'''),
('(''T007'''),
('(''T008'''),
('(''T009'''),
('(''T010'''),
('(''T011'''),
('(''T012'''),
('(''T013'''),
('(''T014'''),
('(''T015'''),
('(''T016'''),
('(''T017'''),
('(''T018'''),
('(''T019'''),
('(''T020'''),
('(''T021'''),
('(''T022'''),
('(''T023'''),
('(''T024'''),
('(''T025'''),
('(''T026'''),
('(''T027'''),
('(''T028'''),
('(''T029'''),
('(''T030'''),
('-- Q1'),
('SELECT status'),
('count(transaction_id) as total_transactions'),
('from transactions'),
('group by 1;'),
('-- Q2'),
('SELECT merchant_name'),
('sum(usd_amount) as total_gmv'),
('from transactions'),
('where status = ''Captured'''),
('group by 1;'),
('--Q3'),
('SELECT'),
('merchant_name'),
('SUM(usd_amount) AS total_gmv'),
('FROM transactions'),
('WHERE status = ''Captured''  -- Filters out Failed and Chargeback rows'),
('GROUP BY merchant_name'),
('ORDER BY total_gmv DESC     -- Changed to DESC to see top merchants first'),
('LIMIT 10;'),
('-- Q4'),
('SELECT'),
('transaction_date'),
('SUM(usd_amount) AS total_daily_gmv'),
('COUNT(transaction_id) AS successful_transactions'),
('FROM transactions'),
('WHERE status = ''Captured'''),
('GROUP BY transaction_date'),
('ORDER BY transaction_date;'),
('--Q5'),
('SELECT'),
('merchant_name'),
('SUM(CASE WHEN status = ''Chargeback'' THEN 1 ELSE 0 END) AS chargeback_count'),
('COUNT(transaction_id) AS total_transactions'),
('(SUM(CASE WHEN status = ''Chargeback'' THEN 1 ELSE 0 END) * 100.0 / COUNT(transaction_id)) AS chargeback_ratio'),
('FROM transactions'),
('GROUP BY merchant_name'),
('HAVING (SUM(CASE WHEN status = ''Chargeback'' THEN 1 ELSE 0 END) * 100.0 / COUNT(transaction_id)) > 1'),
('ORDER BY chargeback_ratio DESC;'),
('--Q6'),
('SELECT gateway_region'),
('AVG(risk_score) AS average_risk'),
('COUNT(transaction_id) AS total_transactions'),
('FROM transactions'),
('GROUP BY gateway_region'),
('HAVING AVG(risk_score) > 50'),
('AND COUNT(transaction_id) > 20;'),
('--Q7'),
('CREATE TABLE users ('),
('user_id VARCHAR(10) PRIMARY KEY'),
('user_name VARCHAR(100)'),
('signup_date DATE'),
('user_region VARCHAR(50)'),
('risk_tier VARCHAR(20)'),
(');'),
('INSERT INTO users (user_id'),
('VALUES'),
('(''U001'''),
('(''U002'''),
('(''U003'''),
('(''U004'''),
('(''U005'''),
('(''U006'''),
('(''U007'''),
('(''U008'''),
('(''U009'''),
('(''U010'''),
('SELECT'),
('u.user_id'),
('u.user_name'),
('t.transaction_date'),
('COUNT(t.transaction_id) AS risky_transaction_count'),
('FROM users u'),
('JOIN transactions t ON u.user_id = t.user_id'),
('WHERE t.status IN (''Failed E05 Timeout'''),
('GROUP BY u.user_id'),
('HAVING COUNT(t.transaction_id) >= 3;'),
('--Q8'),
('SELECT'),
('merchant_name'),
('COUNT(transaction_id) AS chargeback_count'),
('COUNT(DISTINCT user_id) AS unique_affected_users'),
('SUM(usd_amount) AS total_chargeback_amount'),
('FROM transactions'),
('WHERE status = ''Chargeback'''),
('GROUP BY merchant_name'),
('ORDER BY total_chargeback_amount DESC;');
